name: catatan_keuangan
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
  fonts:
    - family: Poppins-bold
      fonts:
        - asset: fonts/Poppins-Bold.ttf
    - family: Poppins-semiBold
      fonts:
        - asset: fonts/Poppins-SemiBold.ttf
    - family: Poppins-regular
      fonts:
        - asset: fonts/Poppins-Regular.ttf
